name: Update Doctors List

on:
  repository_dispatch:
    types: [update_doctors]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update doctors.json
        run: |
          echo '${{ toJson(github.event.client_payload.doctors) }}' > temp.json
          jq -n --argjson doctors "$(cat temp.json)" '{ doctors: $doctors }' > doctors.json
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add doctors.json
          git commit -m "Update doctors list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
